[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Sagatro mechanics
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.yes_pool_flag and not G.GAME.pool_flags[v.yes_pool_flag] then add = nil end"
position = "after"
payload = '''

if Sagatro.config.DisableOtherJokers then
    if v.set == 'Joker' then
        -- Sagatro jokers only
        if not v.saga_group then add = nil end
        
        -- Events that would alter joker pool
        for story, events in pairs(G.GAME.saga_event) do    
            for event, happening in pairs(events) do
                if happening then
                    if G.GAME.saga_spawn_table[story][event] then
                        add = nil
                        for _, key in pairs(G.GAME.saga_spawn_table[story][event]) do
                            if not (G.GAME.used_jokers[v.key] and not pool_opts.allow_duplicates and not next(find_joker("Showman")))
                            and v.unlocked ~= false and v.key == key then
                                add = true
                            end
                        end
                    end
                end
            end
        end
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif _type == 'Joker' then _pool[#_pool + 1] = "j_joker"'''
position = "at"
payload = '''
elseif _type == 'Joker' then
    if Sagatro.config.DisableOtherJokers then
        if G.GAME.saga_event.alice_in_wonderland.cry_into_flood then
            _pool[#_pool + 1] = "j_splash"
        else
            _pool[#_pool + 1] = "j_sgt_white_rabbit"
        end
    else
        _pool[#_pool + 1] = "j_joker"
    end
'''
match_indent = true

# Emult
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local extrafunc = nil"
position = "after"
payload = '''
if not SMODS.Mods["Talisman" or {}].can_load
and not SMODS.Mods["Buffoonery" or {}].can_load
and not SMODS.Mods["Prism" or {}].can_load then
	if eval_type == 'e_mult' then 
		sound = 'sgt_emult'
		amt = amt
		text = '^' .. amt .. " " .. localize("k_mult")
		colour = G.C.DARK_EDITION
		config.type = 'fade'
		config.scale = 0.7
	end
end
'''
match_indent = true