[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Sagatro jokers only
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.yes_pool_flag and not G.GAME.pool_flags[v.yes_pool_flag] then add = nil end"
position = "after"
payload = '''
if SMODS.Mods["Sagatro"].config.DisableOtherJokers then
    if v.set == 'Joker' and not v.saga_group then add = nil end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif _type == 'Joker' then _pool[#_pool + 1] = "j_joker"'''
position = "at"
payload = '''
elseif _type == 'Joker' then _pool[#_pool + 1] = "j_sgt_white_rabbit"
'''
match_indent = true